name: Build Portable Windows Executable

on:
  push:
    branches: [main]

jobs:
  build-32bit:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          architecture: 'x86'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Compile portable executable for x86
        shell: pwsh
        run: |
          $font_dir = python -c "import os, pyfiglet; print(os.path.join(os.path.dirname(pyfiglet.__file__), 'fonts'))"
          pyinstaller --onefile --add-data "$font_dir;pyfiglet/fonts" --name email_toolkit_x86 run.py

      - name: Upload EXE as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: email_toolkit_x86
          path: dist/email_toolkit_x86.exe
  
  build-64bit:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          venv\Scripts\activate

      - name: Install dependencies
        run: pip install -r requirements.txt


      - name: Compile portable executable for x64
        shell: pwsh
        run: |
          $font_dir = python -c "import os, pyfiglet; print(os.path.join(os.path.dirname(pyfiglet.__file__), 'fonts'))"
          pyinstaller --onefile --add-data "$font_dir;pyfiglet/fonts" --name email_toolkit_x64 run.py

      - name: Upload EXE as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: email_toolkit_x64
          path: dist/email_toolkit_x64.exe