name: Build and Release Portable Python Executable

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          venv\Scripts\activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Compile portable executable
        run: pyinstaller --onefile --noconsole --target-arch=x86_64 validator.py

      - name: Create GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.repository.url }}/releases/download/${{ github.ref }}/validator.exe
          asset_path: dist\validator.exe
          name: validator.exe
          label: Portable Python Executable